=== predicador37/lpp/imagen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.uned.es/lpp"
           xmlns:lpp="http://www.uned.es/lpp" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="repositorio" type="lpp:tipoRepositorio" xmlns:lpp="http://www.uned.es/lpp"/>

    <xs:complexType name="tipoPunto">
        <xs:sequence>
            <xs:element name="x" type="xs:double"/>
            <xs:element name="y" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipoForma">
        <xs:sequence>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="borde" type="xs:int"/>
            <xs:element name="opacidad" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoRectangulo">
        <xs:complexContent>
            <xs:extension base="lpp:tipoForma" xmlns="http://www.uned.es/lpp">
                <xs:sequence>
                    <xs:element name="posicion" type="lpp:tipoPunto" xmlns:lpp="http://www.uned.es/lpp"></xs:element>
                    <xs:element name="ancho" type="xs:double"/>
                    <xs:element name="alto" type="xs:double"/>
                </xs:sequence>
            </xs:extension>

        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="tipoCirculo">
        <xs:complexContent>
            <xs:extension base="lpp:tipoForma" xmlns:lpp="http://www.uned.es/lpp">
                <xs:sequence>
                    <xs:element name="centro" type="lpp:tipoPunto" xmlns:lpp="http://www.uned.es/lpp"></xs:element>
                    <xs:element name="radio" type="xs:double"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="tipoElipse">
        <xs:complexContent>
            <xs:extension base="lpp:tipoForma" xmlns:lpp="http://www.uned.es/lpp">
                <xs:sequence>
                    <xs:element name="centro" type="lpp:tipoPunto" xmlns:lpp="http://www.uned.es/lpp"></xs:element>
                    <xs:element name="radio_x" type="xs:double"/>
                    <xs:element name="radio_y" type="xs:double"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="tipoLinea">
        <xs:sequence>
            <xs:element name="punto_inicial" type="lpp:tipoPunto" xmlns:lpp="http://www.uned.es/lpp"></xs:element>
            <xs:element name="punto_final" type="lpp:tipoPunto" xmlns:lpp="http://www.uned.es/lpp"/>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="grosor" type="xs:int"/>
        </xs:sequence>

    </xs:complexType>

    <xs:complexType name="tipoPoligono">
        <xs:complexContent>
            <xs:extension base="lpp:tipoForma" xmlns:lpp="http://www.uned.es/lpp">
                <xs:sequence>
                    <xs:element name="punto" type="lpp:tipoPunto" minOccurs="3" maxOccurs="unbounded"
                                xmlns:lpp="http://www.uned.es/lpp"></xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="tipoPolilinea">
        <xs:sequence>
            <xs:element name="punto" type="lpp:tipoPunto" minOccurs="3" maxOccurs="unbounded"
                        xmlns:lpp="http://www.uned.es/lpp"></xs:element>
            <xs:element name="color" type="xs:string"/>

        </xs:sequence>

    </xs:complexType>


    <xs:complexType name="tipoImagen">

        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="rectangulo" type="lpp:tipoRectangulo" xmlns:lpp="http://www.uned.es/lpp"/>
            <xs:element name="circulo" type="lpp:tipoCirculo" xmlns:lpp="http://www.uned.es/lpp"/>
            <xs:element name="eclipse" type="lpp:tipoElipse" xmlns:lpp="http://www.uned.es/lpp"/>
            <xs:element name="linea" type="lpp:tipoLinea" xmlns:lpp="http://www.uned.es/lpp"/>
            <xs:element name="poligono" type="lpp:tipoPoligono" xmlns:lpp="http://www.uned.es/lpp"/>
            <xs:element name="polilinea" type="lpp:tipoPolilinea" xmlns:lpp="http://www.uned.es/lpp"/>
        </xs:choice>
        <xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType>


    <xs:complexType name="tipoRepositorio">
        <xs:sequence>
            <xs:element name="imagen" type="lpp:tipoImagen" minOccurs="1" maxOccurs="unbounded"
                        xmlns:lpp="http://www.uned.es/lpp"/>
        </xs:sequence>
    </xs:complexType>


</xs:schema>

=== predicador37/lpp/imagen.xml
<repositorio xmlns="http://www.uned.es/lpp" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="file:///./imagen.xsd">
  <!--1 or more repetitions:-->
  <imagen id="string">
    <!--You have a CHOICE of the next 6 items at this level-->
    <rectangulo>
      <color>string</color>
      <borde>3</borde>
      <opacidad>3</opacidad>
      <posicion>
        <x>1.051732E7</x>
        <y>1.051732E7</y>
      </posicion>
      <ancho>1.051732E7</ancho>
      <alto>1.051732E7</alto>
    </rectangulo>
    <circulo>
      <color>string</color>
      <borde>3</borde>
      <opacidad>3</opacidad>
      <centro>
        <x>1.051732E7</x>
        <y>1.051732E7</y>
      </centro>
      <radio>1.051732E7</radio>
    </circulo>
    <eclipse>
      <color>string</color>
      <borde>3</borde>
      <opacidad>3</opacidad>
      <centro>
        <x>1.051732E7</x>
        <y>1.051732E7</y>
      </centro>
      <radio_x>1.051732E7</radio_x>
      <radio_y>1.051732E7</radio_y>
    </eclipse>
    <linea>
      <punto_inicial>
        <x>1.051732E7</x>
        <y>1.051732E7</y>
      </punto_inicial>
      <punto_final>
        <x>1.051732E7</x>
        <y>1.051732E7</y>
      </punto_final>
      <color>string</color>
      <grosor>3</grosor>
    </linea>
    <poligono>
      <color>string</color>
      <borde>3</borde>
      <opacidad>3</opacidad>
      <!--3 or more repetitions:-->
      <punto>
        <x>1.051732E7</x>
        <y>1.051732E7</y>
      </punto>
      <punto>
        <x>1.051732E7</x>
        <y>1.051732E7</y>
      </punto>
      <punto>
        <x>1.051732E7</x>
        <y>1.051732E7</y>
      </punto>
    </poligono>
    <polilinea>
      <!--3 or more repetitions:-->
      <punto>
        <x>1.051732E7</x>
        <y>1.051732E7</y>
      </punto>
      <punto>
        <x>1.051732E7</x>
        <y>1.051732E7</y>
      </punto>
      <punto>
        <x>1.051732E7</x>
        <y>1.051732E7</y>
      </punto>
      <color>string</color>
    </polilinea>
  </imagen>
</repositorio>
